from restaurant.serializers.order import OrderSerializer
from restaurant.serializers.order_item import OrderItemSerializer
from restaurant.serializers.customers import CustomerSerializer ,CustomerSignUpSerializer ,CustomerLoginSerializer
from restaurant.serializers.discount import DiscountSerializer
from restaurant.serializers.ingredient import IngredientSerializer
from restaurant.serializers.menu_item import MenuItemSerializer
from restaurant.serializers.order_item_modification import OrderItemModificationSerializer
from restaurant.serializers.payment import PaymentSerializer
from restaurant.serializers.table import TableSerializer, CreateTableSerializer, TableAvailabilitySerializer
from restaurant.serializers.reservation import (
    ReservationSerializer, CreateReservationSerializer, UpdateReservationSerializer,
    ReservationStatusUpdateSerializer, ReservationAvailabilitySerializer
)