# Generated by Django 4.2.11 on 2025-05-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='order_item_ingredients', to='restaurant.ingredient'),
        ),
    ]
