# Generated by Django 4.2.11 on 2025-06-08 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_table_reservation_reservation_unique_table_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='restaurant.discount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='restaurant.order')),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('customer', 'discount')},
            },
        ),
    ]
